platform :ios, '11.0'
use_frameworks!

pod "Parse"
pod ‘Alamofire’
pod 'AlamofireImage'
pod 'DropDown'
pod 'SPAlert'

target 'Purdue Books' do
  # Pods for Login-Designs
  pod 'IQKeyboardManagerSwift'
end
